sudo: required

language: java

jdk: 
  - oraclejdk8

before_install:
- curl -sL http://bit.ly/jpm4j >jpm4j.jar
- sudo java -jar jpm4j.jar -g init
- sudo jpm install com.codacy:codacy-coverage-reporter:assembly

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn test

after_success:
- codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml  --prefix src/main/java/